# Generated by Django 5.2.10 on 2026-01-18 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yieldlog',
            name='user',
        ),
        migrations.CreateModel(
            name='CropRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_value', models.FloatField(verbose_name='Nitrogen')),
                ('p_value', models.FloatField(verbose_name='Phosphorus')),
                ('k_value', models.FloatField(verbose_name='Potassium')),
                ('ph_value', models.FloatField(verbose_name='Soil pH')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('recommended_crop', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YieldPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.FloatField(default=0.0)),
                ('predicted_yield', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RecommendationLog',
        ),
        migrations.DeleteModel(
            name='YieldLog',
        ),
    ]
